---
kind: pipeline
name: right-sizer

steps:
- name: publish  
  image: plugins/gcr
  settings:
    registry: eu.gcr.io
    repo: moss-work/right-sizer
    tags: latest
    json_key:
      from_secret: MW_PUSH_CREDS
  when:
    event: push
    branch: master
- name: deploy
  image: mosstech/drone-gke-deployer:latest
  environment:
    NAMESPACE:
      from_secret: MW_NAMESPACE
    GCP_PROJECT_ID:
      from_secret: MW_PROJECT
    K8S_DEPLOYER_CREDS:
      from_secret: MW_K8S_DEPLOYER
    K8S_CLUSTER_NAME:
      from_secret: MW_K8S_CLUSTER_NAME
  commands:
  - ./go deploy
  when:
    event: push
    branch: master
---
kind: signature
hmac: a6b1871af273972ab45c99ace1c37f35467c2ca0b1cbc5ead1bbf08d252f95dd

...
